// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBipQgcm8AjjDZHPdatvxsfUzk2FygxjZw',
    appId: '1:581326620290:web:0be22e598b31b6ef8d969b',
    messagingSenderId: '581326620290',
    projectId: 'bbbuddies-d3bb6',
    authDomain: 'bbbuddies-d3bb6.firebaseapp.com',
    databaseURL: 'https://bbbuddies-d3bb6-default-rtdb.firebaseio.com',
    storageBucket: 'bbbuddies-d3bb6.appspot.com',
    measurementId: 'G-73N0GGRMVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3gN3JvmY-RgZbk0XqB_0RlbJNuBOkBk',
    appId: '1:581326620290:android:2328fc8487eff5e98d969b',
    messagingSenderId: '581326620290',
    projectId: 'bbbuddies-d3bb6',
    databaseURL: 'https://bbbuddies-d3bb6-default-rtdb.firebaseio.com',
    storageBucket: 'bbbuddies-d3bb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCid7K2yODLp2Ct_YvlEecWeBnBTr4yzXg',
    appId: '1:581326620290:ios:18231371b9bcf2398d969b',
    messagingSenderId: '581326620290',
    projectId: 'bbbuddies-d3bb6',
    databaseURL: 'https://bbbuddies-d3bb6-default-rtdb.firebaseio.com',
    storageBucket: 'bbbuddies-d3bb6.appspot.com',
    iosBundleId: 'com.BudgetBuddies.budgetBuddies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBipQgcm8AjjDZHPdatvxsfUzk2FygxjZw',
    appId: '1:581326620290:web:f7c0f9d983c90da08d969b',
    messagingSenderId: '581326620290',
    projectId: 'bbbuddies-d3bb6',
    authDomain: 'bbbuddies-d3bb6.firebaseapp.com',
    databaseURL: 'https://bbbuddies-d3bb6-default-rtdb.firebaseio.com',
    storageBucket: 'bbbuddies-d3bb6.appspot.com',
    measurementId: 'G-3TL2GK1T8Z',
  );

}